version: "3.2"

services:
  # app:
  #   queue: user.queue
  #   exchange: user.exchange
  #   routingkey: user.routingkey
  #   message: Message has been sent Successfully..
  rabbitmq:
    image: rabbitmq:3-management
    container_name: 'rabbitmq'
    ports:
      - "6500:5672"
      - "15672:15672"
    volumes:
      - ./db:/var/lib/rabbitmq
    environment:
      - queue=spring-boot
      - exchange=exchange
      - routingkey=routingkey
      - message=Message has been sent Successfully..
    
  
