version: "3.2"

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: 'rabbitmq'
    ports:
      - "6500:5672"
      - "15672:15672"
    volumes:
      - ./db:/var/lib/rabbitmq
  prometheus:
    container_name: "prometheus"
    image: prom/prometheus:v2.42.0
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
  grafana:
    container_name: "grafana"
    image: grafana/grafana:9.3.6
    ports:
      - "3000:3000"
    
  
